# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            IEMS5780
tagline:          'CUHK MScIE IEMS5780'
description:      'CUHK MScIE IEMS5780 Building and Deploying Scalable Machine Learning Services (2019-2020 Term 1)'
url:              http://iems5780.albertauyeung.com/
baseurl:          /

author:
  name:           'Albert Au Yeung'
  url:            http://www.albertauyeung.com/

#plugins: [jekyll-paginate]
#paginate:         5

# Custom vars
version:          2.1.0

